services:
  # Redis for Celery backend
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  
  # The main processes (Gunicorn + Celery)
  server:
    build:
      context: .
    ports:
      - 8000:8000
    depends_on:
      - redis
